services:
   addresspamadmin:
        class: Admin\AdminBundle\Admin\AddressSpamAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Email Address Blacklist Filter" }
        arguments:
            - ~
            - Admin\AdminBundle\Entity\AddressSpam
            - ~
        calls:
            - [ setTranslationDomain, [AdminAdminBundle]]
   messagespamadmin:
        class: Admin\AdminBundle\Admin\MessageSpamAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Message Blacklist Filter" }
        arguments:
            - ~
            - Admin\AdminBundle\Entity\MessageSpam
            - ~
        calls:
            - [ setTranslationDomain, [AdminAdminBundle]]
   videoadmin:
        class: Admin\AdminBundle\Admin\VideoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Biography" }
        arguments:
            - ~
            - Admin\AdminBundle\Entity\Video
            - ~
        calls:
            - [ setTranslationDomain, [AdminAdminBundle]]
   emailadmin:
        class: Admin\AdminBundle\Admin\EmailAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Email" }
        arguments:
            - ~
            - Admin\AdminBundle\Entity\Email
            - ~
        calls:
            - [ setTranslationDomain, [AdminAdminBundle]]
    
  