Admin\AdminBundle\Entity\Video:
    type: entity
    table: null
    repositoryClass: Admin\AdminBundle\Entity\VideoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: text
        url:
            type: text
        description:
            type: text
    lifecycleCallbacks: {  }
